version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8800
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8800:8800
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dj_chappie
      - POSTGRES_PASSWORD=dj_chappie
      - POSTGRES_DB=Chappie_db

volumes:
  postgres_data:
